######################################## SHINY UI ####################################


######### FUNCTION INFO #########
# renderUI(expr) — server-side builder that returns UI tags generated by expr for a paired uiOutput.
# div(..., class = NULL, style = NULL) — HTML <div> tag; group UI elements; add CSS with class/style.
# em(...) — HTML emphasis <em> tag; renders italic text.
# tagList(...) — combine multiple UI tags into a single return value (handy in renderUI).
# wellPanel(...) — Bootstrap “well” container; visually groups controls.
# fluidRow(...) — Bootstrap row for grid layout; usually contains column(width, ...).
# selectInput(inputId, label, choices, selected = NULL, multiple = FALSE) — dropdown selector.
# numericInput(inputId, label, value, min = NA, max = NA, step = NA) — numeric textbox with spinners.
# actionButton(inputId, label, icon = NULL) — clickable button; increments input$inputId on each click.
# uiOutput(outputId) — placeholder in the UI where a renderUI result is inserted.
# setdiff(x, y) — base set difference; elements in x not in y.
# observe(expr, ignoreInit = FALSE, once = FALSE) : read reactive values and call reactive expressions, and will automatically re-execute when those dependencies change (no explicit trigger). But unlike reactive expressions, it doesn't yield a result and can't be used as an input to other reactive expressions. Observers are good for their side effects : performing I/O (input (take in data) /output (print or save data))
# observeEvent is an input function in Shiny in which a certain code is executed when an event of the user’s choice happens. It observes an event and runs the given expression as soon as the event is triggered, an example is a button click or a value change in a text field

# local(expr, envir = new.env()) — evaluate expr in a fresh environment; often used in loops to capture loop variables for closures.
# checkboxInput(inputId, label, value = FALSE) — single TRUE/FALSE toggle.
# req(..., cancelOutput = TRUE) — validate inputs; if any are NULL/FALSE/length 0, abort the reactive and (optionally) blank the output.
# withProgress(message = "", value = 0, expr) — show a progress bar while running expr; initialize with value in [0,1].
# incProgress(amount, detail = NULL) — advance the current progress bar by amount (fraction of 1).
# identical(x, y) — strict equality test (type + value); returns TRUE only if exactly the same.
# input[[paste0("hmc_adaptive_", id)]] (what’s the point?) — dynamically read a per-card input by constructing its id from a prefix and the card’s id (lets you have many cards: hmc_adaptive_1, _2, …).
# updateCheckboxGroupInput(session, inputId, choices = NULL, selected = NULL, label = NULL) — modify a checkbox group’s choices/selection from the server.
# unlist(x, recursive = TRUE, use.names = TRUE) — flatten a list to a vector; useful for collecting names or concatenating small vectors.
# renderTable(expr, striped = FALSE, bordered = FALSE, spacing = c("s","m","l")) — render a static HTML table from a data frame or matrix.
# reactive(expr) — declare a cached reactive expression that recomputes when its dependencies change (used like a read-only variable).
# curves_reactive() — your app’s reactive that builds matrices of advanced diagnostic curves (MSE/DT/ESJD) for the currently selected runs/parameters, padding lengths for plotting.
# renderPlot(expr, width = "auto", height = "auto", res = 96) — render a base/ggplot built in expr.
# downloadHandler(filename, content, contentType = NULL) — define a downloadable file; filename() returns a name; content(file) writes to that path.
# Sys.Date() — current date as Date; handy for timestamped filenames.
# make_plot(M, ylab_txt) — your helper that takes a curves matrix M (rows = iterations, cols = runs) and draws a matplot with legend and ylab_txt.


#########################  HELPER
bind_curves <- function(named_list) {
  if (!length(named_list)) return(NULL)
  L <- max(vapply(named_list, length, 0L))
  M <- sapply(named_list, function(v) { length(v) <- L; v })
  colnames(M) <- names(named_list)
  M
}
#########################

ui <- fluidPage(
  # Top page title shown at the top of the app
  titlePanel("MCMC dashboard"),

  navset_pill(
    id = "tab",

    # ---------------- Page A: Run chains ----------------
    nav_panel(
      "Chains Settings",
      fluidRow(
        # LEFT: global chain settings + actions
        column(
          4,
          h4("Chain settings"),
          textInput(
            "posterior",
            "posterior_name",
            "eight_schools-eight_schools_noncentered"
          ),
          numericInput("warmup", "training iterations (warmup)", 200,  min = 0, step = 100),
          numericInput("main",   "testing iterations (main)",    2000, min = 1, step = 100),
          numericInput("nchains","number of chains per run", 2, min = 1),
          numericInput("thin",   "thin", 1, min = 1),
          tags$hr(),
          actionButton("add",   "➕ Add chain"),
          actionButton("clear", "🗑️ Clear all"),
          tags$hr(),
          actionButton("run", "▶ Run all", class = "btn-primary")
        ),
        # RIGHT: dynamic list of configuration cards
        column(
          8,
          h4("Chain configurations"),
          uiOutput("cards")
        )
      )
    ),

    # ---------------- Page B: Tables ----------------
    nav_panel(
      "Diagnostic Tables",
      fluidRow(
        column(
          12,
          h4("Basic diagnostics table (from basic_diagnostics)"),
          fluidRow(
            column(6, uiOutput("var_picker")),
            column(6, uiOutput("run_picker"))
          ),
          div(
            style = "margin-top: 8px;",
            downloadButton("dl_table", "Download table (CSV)")
          ),
          tags$hr(),
          tableOutput("tbl")
        )
      )
    ),

    # ---------------- Page C: Graphs ----------------
    nav_panel(
      "Diagnostic Graphs",
      fluidRow(
        column(
          12,
          h4("Advanced diagnostics (curves across runs)"),
          fluidRow(
            column(
              4,
              radioButtons(
                "which_curve",
                "Curve",
                c(
                  "Running MSE (mean)"                 = "mse",
                  "Running DT (log-variance distance)" = "dt",
                  "Running ESJD"                       = "esjd"
                ),
                inline = FALSE
              )
            ),
            column(
              8,
              checkboxGroupInput(
                "runs_for_plot",
                "Runs to include",
                choices = NULL
              ),
              div(
                style = "margin-top: 8px;",
                downloadButton("dl_plot_png", "Download PNG"),
                downloadButton("dl_plot_pdf", "Download PDF")
              )
            )
          ),
          plotOutput("plot_curve", height = 360)
        )
      )
    )
  )
)

######################################## SHINY SERVER ####################################

server <- function(input, output, session) {

  rv <- reactiveValues(ids = integer(0), next_id = 1, results = NULL, truth = NULL)

  #------------------------- ADD / CLEAR CARDS -----------------------------
  observeEvent(input$add, {
    rv$ids     <- c(rv$ids, rv$next_id)
    rv$next_id <- rv$next_id + 1
  })

  observeEvent(input$clear, {
    rv$ids     <- integer(0)
    rv$results <- NULL
  })

  #------------------------- CARDS UI (dynamic) -----------------------------
  output$cards <- renderUI({
    if (!length(rv$ids))
      return(div(em("Click ➕ Add chain to create a configuration.")))

    tagList(lapply(rv$ids, function(id) {
      wellPanel(
        fluidRow(
          column(
            3,
            selectInput(
              paste0("method_", id),
              "sampler",
              c("bimodal", "barker", "amala", "amh", "hmc"),
              selected = "hmc"
            )
          ),
          column(
            3,
            selectInput(
              paste0("adapter_", id),
              "adapter",
              c("adapter1", "adapter2", "None"),
              selected = "adapter1"
            )
          ),
          column(
            3,
            numericInput(
              paste0("scale_", id),
              "scale (optional)",
              NA_real_,
              step = 0.1
            )
          ),
          column(
            3,
            actionButton(
              paste0("remove_", id),
              "Remove",
              class = "btn-sm"
            )
          )
        ),
        uiOutput(paste0("adapter_opts_", id)),
        uiOutput(paste0("hmc_opts_", id))
      )
    }))
  })

  #------------------------- REMOVE A CARD ----------------------------------
  observe({
    lapply(rv$ids, function(id) {
      observeEvent(input[[paste0("remove_", id)]], {
        rv$ids <- setdiff(rv$ids, id)
      }, ignoreInit = TRUE)
    })
  })

  #------------------------- ADAPTER-SPECIFIC OPTIONS -----------------------
  observe({
    lapply(rv$ids, function(id) {
      local({
        idL <- id
        output[[paste0("adapter_opts_", idL)]] <- renderUI({
          ad <- input[[paste0("adapter_", idL)]]
          if (is.null(ad)) return(NULL)

          if (ad == "adapter1") {
            fluidRow(
              column(
                3,
                numericInput(
                  paste0("a1_kappa_", idL),
                  "kappa",
                  0.60,
                  step = 0.05
                )
              ),
              column(
                3,
                numericInput(
                  paste0("a1_tau_", idL),
                  "tau_star",
                  0.40,
                  step = 0.05
                )
              )
            )
          } else if (ad == "adapter2") {
            fluidRow(
              column(
                3,
                numericInput(
                  paste0("a2_kappa_", idL),
                  "kappa",
                  0.60,
                  step = 0.05
                )
              ),
              column(
                3,
                numericInput(
                  paste0("a2_gamma_", idL),
                  "gamma",
                  0.05,
                  step = 0.01
                )
              ),
              column(
                3,
                numericInput(
                  paste0("a2_io_", idL),
                  "iteration_offset",
                  10,
                  step = 1
                )
              ),
              column(
                3,
                numericInput(
                  paste0("a2_tau_", idL),
                  "tau_star",
                  0.40,
                  step = 0.05
                )
              )
            )
          } else {
            NULL
          }
        })
      })
    })
  })

  #------------------------- HMC-SPECIFIC OPTIONS ---------------------------
  observe({
    lapply(rv$ids, function(id) {
      local({
        idL <- id

        output[[paste0("hmc_opts_", idL)]] <- renderUI({
          # Only show this block if the method for this card is HMC
          m <- input[[paste0("method_", idL)]]
          if (!identical(m, "hmc")) return(NULL)

          # Current selected mode for this card (may be NULL the very first time)
          mode <- input[[paste0("hmc_mode_", idL)]]
          if (is.null(mode)) mode <- "sample_n_step"   # default = “Adaptive”

          tagList(
            # --- HMC mode selector (your requested selectInput) ---
            selectInput(
              paste0("hmc_mode_", idL),
              "Select options below:",
              list(
                "Fixed Step"         = "fixed_step",
                "Adaptive"           = "sample_n_step",
                "Auxiliary Function" = "aux"
              ),
              selected = mode   # <<< THIS IS THE KEY FIX
            ),

            # --- Only show the numeric input when Fixed Step is selected ---
            if (identical(mode, "fixed_step")) {
              numericInput(
                paste0("hmc_nstep_", idL),
                "Number of leapfrog steps",
                value = 10,
                min   = 1,
                step  = 1
              )
            } else {
              NULL  # nothing extra when Adaptive / Auxiliary
            }
          )
        })
      })
    })
  })

  #------------------------- RUN ALL CONFIGURATIONS -------------------------
  observeEvent(input$run, {
    req(length(rv$ids) > 0)

    withProgress(message = "Running chains…", value = 0, {
      inf <- posterior_draws(name = input$posterior)
      rv$truth <- inf

      results <- list()

      for (k in seq_along(rv$ids)) {
        id <- rv$ids[k]
        incProgress((k - 1) / max(1, length(rv$ids)),
                    detail = paste("chain config", id))

        method <- input[[paste0("method_", id)]]
        ad_sel <- input[[paste0("adapter_", id)]]
        scale  <- input[[paste0("scale_",   id)]]

        adapters_arg <- switch(
          ad_sel,
          "adapter1" = "adapter1",
          "adapter2" = "adapter2",
          "None"     = NULL
        )

        kappa            <- 0.6
        gamma            <- 0.05
        iteration_offset <- 10
        tau_star         <- 0.40

        if (identical(adapters_arg, "adapter1")) {
          kappa    <- input[[paste0("a1_kappa_", id)]]
          tau_star <- input[[paste0("a1_tau_",   id)]]
        } else if (identical(adapters_arg, "adapter2")) {
          kappa            <- input[[paste0("a2_kappa_", id)]]
          gamma            <- input[[paste0("a2_gamma_", id)]]
          iteration_offset <- input[[paste0("a2_io_",    id)]]
          tau_star         <- input[[paste0("a2_tau_",   id)]]
        }

        n_step_arg        <- NULL
        sample_n_step_arg <- NULL
        sample_aux_arg    <- NULL

        if (identical(method, "hmc")) {
          mode <- input[[paste0("hmc_mode_", id)]]
          if (is.null(mode)) mode <- "sample_n_step"  # default = adaptive

          if (mode == "fixed_step") {
            # Fixed number of leapfrog steps, no randomisation, no aux
            n_step_arg        <- input[[paste0("hmc_nstep_", id)]]
            sample_n_step_arg <- NULL
            sample_aux_arg    <- FALSE

          } else if (mode == "sample_n_step") {
            # Random n_step (HMC chooses each iteration), no auxiliary
            n_step_arg        <- NULL
            sample_n_step_arg <- TRUE
            sample_aux_arg    <- FALSE

          } else if (mode == "aux") {
            # Random n_step + auxiliary momentum refresh
            n_step_arg        <- NULL
            sample_n_step_arg <- TRUE
            sample_aux_arg    <- TRUE

          } else {
            # Fallback: treat as adaptive
            n_step_arg        <- NULL
            sample_n_step_arg <- TRUE
            sample_aux_arg    <- FALSE
          }
        }

        run <- sample_mcmc(
          method           = method,
          name             = input$posterior,
          warm_up          = input$warmup,
          main             = input$main,
          adapters         = adapters_arg,
          scale            = if (is.na(scale)) NULL else scale,
          thin             = input$thin,
          chains           = input$nchains,
          kappa            = kappa,
          iteration_offset = iteration_offset,
          gamma            = gamma,
          tau_star         = tau_star,
          n_step           = n_step_arg,
          sample_n_step    = sample_n_step_arg,
          sample_auxiliary = sample_aux_arg,
          plot             = FALSE,
          save_plot        = FALSE
        )

        mcl        <- run$mcl
        tab        <- run$diag_basic
        diag_extra <- run$diag_extra
        curves     <- if (!is.null(diag_extra)) diag_extra$curves else NULL

        label <- paste0(
          method,
          if (!is.null(adapters_arg)) paste0("_", adapters_arg) else "",
          if (identical(method, "hmc")) {
            paste0(
              "_",
              if (is.null(n_step_arg)) "noStep" else paste0("n", n_step_arg),
              "_aux", sample_aux_arg
            )
          } else "",
          "_run", id
        )

        results[[label]] <- list(
          mcl        = mcl,
          tab        = tab,
          curves     = curves,
          diag_extra = diag_extra
        )
      }

      rv$results <- results

      updateCheckboxGroupInput(
        session,
        "runs_for_plot",
        choices  = names(results),
        selected = names(results)
      )

      all_vars <- unique(unlist(lapply(results, function(x) {
        if ("variable" %in% names(x$tab)) x$tab$variable else NULL
      })))

      output$var_picker <- renderUI({
        if (is.null(all_vars) || !length(all_vars)) return(NULL)
        selectizeInput(
          "vars",
          "Filter parameters (affects table)",
          choices  = all_vars,
          selected = all_vars,
          multiple = TRUE
        )
      })

      output$run_picker <- renderUI({
        checkboxGroupInput(
          "runs_for_table",
          "Runs in table",
          choices  = names(results),
          selected = names(results)
        )
      })
    })
  })

  #------------------------- BASIC DIAGNOSTICS TABLE ------------------------
  output$tbl <- renderTable({
    req(rv$results, input$runs_for_table)

    out <- lapply(input$runs_for_table, function(lbl) {
      tb <- rv$results[[lbl]]$tab
      if (!is.null(input$vars) && "variable" %in% names(tb)) {
        tb <- tb[tb$variable %in% input$vars, , drop = FALSE]
      }
      cbind(Sampler = lbl, tb)
    })

    do.call(rbind, out)
  }, striped = TRUE, bordered = TRUE, spacing = "xs", width = "100%")

  #------------------------- ADVANCED CURVES (REACTIVE) ---------------------
  curves_reactive <- reactive({
    req(rv$results)

    sel_runs <- input$runs_for_plot
    if (!length(sel_runs))
      return(list(mse = NULL, dt = NULL, esjd = NULL))

    out_mse  <- list()
    out_dt   <- list()
    out_esjd <- list()

    for (lbl in sel_runs) {
      curv <- rv$results[[lbl]]$curves
      if (is.null(curv)) next

      if (!is.null(curv$mse))   out_mse[[lbl]]  <- curv$mse
      if (!is.null(curv$dt))    out_dt[[lbl]]   <- curv$dt
      if (!is.null(curv$esjd))  out_esjd[[lbl]] <- curv$esjd
    }

    list(
      mse  = if (length(out_mse))  bind_curves(out_mse)  else NULL,
      dt   = if (length(out_dt))   bind_curves(out_dt)   else NULL,
      esjd = if (length(out_esjd)) bind_curves(out_esjd) else NULL
    )
  })

  #------------------------- PLOT HELPERS -----------------------------------
  make_plot <- function(M, ylab_txt) {
    if (is.null(M)) {
      plot.new()
      title("No data for this curve")
      return(invisible(NULL))
    }

    keep <- intersect(input$runs_for_plot, colnames(M))
    if (!length(keep)) {
      plot.new()
      title("No selected runs")
      return(invisible(NULL))
    }

    Y <- M[, keep, drop = FALSE]

    matplot(
      Y,
      type = "l",
      lty  = 1,
      xlab = "Iteration",
      ylab = ylab_txt,
      col  = seq_len(ncol(Y))
    )
    legend(
      "topright",
      legend = colnames(Y),
      lty    = 1,
      col    = seq_len(ncol(Y)),
      cex    = 0.75
    )
  }

  output$plot_curve <- renderPlot({
    crv <- curves_reactive()
    switch(
      input$which_curve,
      mse  = make_plot(crv$mse,  "Running MSE of mean"),
      dt   = make_plot(crv$dt,   "Running DT (log-variance distance)"),
      esjd = make_plot(crv$esjd, "Running ESJD")
    )
  })

  #------------------------- TABLE DOWNLOAD (CSV) ---------------------------
  output$dl_table <- downloadHandler(
    filename = function() sprintf("diagnostics_table_%s.csv", Sys.Date()),
    content = function(file) {
      req(rv$results, input$runs_for_table)
      out <- lapply(input$runs_for_table, function(lbl) {
        tb <- rv$results[[lbl]]$tab
        if (!is.null(input$vars) && "variable" %in% names(tb)) {
          tb <- tb[tb$variable %in% input$vars, , drop = FALSE]
        }
        cbind(Sampler = lbl, tb)
      })
      write.csv(do.call(rbind, out), file, row.names = FALSE)
    }
  )

  #------------------------- PLOT DOWNLOAD (PNG/PDF) ------------------------
  plot_export <- function(path, dev = c("png", "pdf")) {
    crv <- curves_reactive()

    ylab_txt <- switch(
      input$which_curve,
      mse  = "Running MSE of mean",
      dt   = "Running DT (log-variance distance)",
      esjd = "Running ESJD"
    )

    M <- switch(
      input$which_curve,
      mse  = crv$mse,
      dt   = crv$dt,
      esjd = crv$esjd
    )

    if (dev[1] == "png") {
      png(path, width = 900, height = 600, res = 120)
    } else {
      pdf(path, width = 9, height = 6)
    }

    make_plot(M, ylab_txt)
    dev.off()
  }

  output$dl_plot_png <- downloadHandler(
    filename = function() sprintf("%s_%s.png", input$which_curve, Sys.Date()),
    content  = function(file) plot_export(file, "png")
  )

  output$dl_plot_pdf <- downloadHandler(
    filename = function() sprintf("%s_%s.pdf", input$which_curve, Sys.Date()),
    content  = function(file) plot_export(file, "pdf")
  )
}

shinyApp(ui, server)
